spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/skone
      driver-class-name: org.h2.Driver
      username: sa
      password:
  servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 215MB

  h2:
    console:
      path: /h2console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql: debug